export { default as HeaderMain } from './HeaderMain'
export { default as SearchResultsView } from './SearchResult'
export { default as FooterView } from './Footer'
export { default as BodyGamesView} from './BodyGames'
export { default as ResponsiveAppBar } from './AppBar'